version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app-frontend
  
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=NG
    volumes:
      - ./back-end:/app-backend
  db:
    image: postgres:12
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=NG
    restart: 'always'